### ISSUE TITLE
Which repo to progress the NRT QC software topics please

### ISSUE THREAD

**Issue by justinbuck** [OceanGlidersCommunity/meeting_notes#14]
@castelao @soerenthomsen  which repo should we be raising the new issues to progress NRT QC in please?

**Comment by soerenthomsen** [comment]
I think if the questions are parameter specific it should be done in the SOPs RTQC sections. 

For Oxygen issues [here](https://github.com/OceanGlidersCommunity/Oxygen_SOP/issues), RTQC Section [here](https://oceangliderscommunity.github.io/Oxygen_SOP/sections/oxygen_rtqc.html) (tomorrow's oxygen session will also be important for this). The v1.0.0 of the RTQC chapter for now has been drafted by @catsch @cgourcuf et al but we are happy to revise it and have new people on board!

For Salinity issues [here](https://github.com/OceanGlidersCommunity/Salinity_SOP/issues), RTQC Section [here](https://oceangliderscommunity.github.io/Salinity_SOP/sections/salinity_rtqc.html) (WIP by Gui at the moment)

But Gui is also preparing a general RTQC repo which is privat for now.

Also tagging some other folks here: @tomhull @isgiddy

**Comment by soerenthomsen** [comment]
What I envision is that at least the relevant packages are listed in the chapters including a few sentences of what they can or cannot do in terms of NRT-QC.

**Comment by soerenthomsen** [comment]
I think this issue can be closed.
