### ISSUE TITLE
Completion of note from the Friday plenary

### ISSUE THREAD

**Issue by justinbuck** [OceanGlidersCommunity/meeting_notes#25]
@emmerbodc @vturpin @soerenthomsen 
Could you add you summary slides and brief note to the Friday session page please?
https://github.com/OceanGlidersCommunity/meeting_notes/blob/main/plenary_session_24th_June_2022.md

**Comment by soerenthomsen** [comment]
I sent Victor my slides as he wanted to merge them all into one file and upload it. 
Will add some notes
