### ISSUE TITLE
Add pdfs of Chla talks 

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/meeting_notes#5]
@vturpin and @catsch could you make a pdf of your talks and upload it to this repo. You have writing access and just should be able to do this here:
<img width="993" alt="Screenshot 2022-06-22 at 13 06 48" src="https://user-images.githubusercontent.com/32633545/175014578-e00872d3-1290-4c49-a805-80e93473dc9e.png">

**Comment by soerenthomsen** [comment]
@callumrollo and @justinbuck and others are you willing to help documenting the workshop notes? This might also help GROOM reporting to be more effective as they can simply download or link to the files here.

**Comment by vturpin** [comment]
Done, PR #11
